pod "CBPWordPress", :path => "../CBPWordPress.podspec"
pod 'TOWebViewController', '~> 2.0.5'
pod 'NSString-HTML', '~> 0.0'
pod 'MHVideoPhotoGallery', '~> 1.6'
pod 'SVPullToRefresh', '~> 0.4'
pod 'SORelativeDateTransformer', '~> 1.1'
pod 'JBWhatsAppActivity', '~> 1.0'
pod 'GooglePlusShareActivity', '~> 0.2'
